"""
Django settings for mi_web project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- Configuración Inteligente ---
if 'DATABASE_URL' in os.environ:
    # --- Configuración para Producción (Render) ---
    SECRET_KEY = os.environ.get('SECRET_KEY') # Lee de Render
    DEBUG = False
    ALLOWED_HOSTS = ['intranet-centro-odontologico-monfer-spa.onrender.com'] # Asegúrate que esto esté bien
    CSRF_TRUSTED_ORIGINS = ['https://intranet-centro-odontologico-monfer-spa.onrender.com']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Base de datos de Render
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # --- Configuración para Desarrollo Local (Tu PC) ---
    SECRET_KEY = 'django-insecure-zunad+1--#c)p9emx-!#qma5!0*0+*wrqu9@!-w#30ifm!md#d' # Clave local
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    # Base de datos local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'mi_sitio_db',        # O monfer_db, el que uses
            'USER': 'postgres',
            'PASSWORD': 'perlita',       # Tu contraseña local
            'HOST': 'localhost',
            'PORT': '5433',            # Asegúrate de que este puerto sea correcto
        }
    }
    # No fuerces HTTPS localmente
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# --- Resto de la configuración (común para ambos entornos) ---

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'odontologia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Asegúrate que Whitenoise esté instalado
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mi_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # <-- ESTA LÍNEA FALTABA
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_web.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i1n/

LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # Para encontrar tu CSS personalizado
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración de Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "Intranet Monfer",
    "site_header": "Monfer SPA",
    "site_logo": None, # Puedes poner 'images/tu_logo.png' si lo pones en static/images
    "welcome_sign": "Bienvenido a la Intranet de Monfer SPA",
    "copyright": "Monfer SPA Ltd.",
    "theme": "litera", # Tema principal
    "custom_css": "css/admin_custom.css", # Tu CSS personalizado
}

# Redirección después del login
LOGIN_REDIRECT_URL = '/dashboard/'