# Generated by Django 5.2.7 on 2025-10-15 01:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0002_odontologo_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Atención')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Examen')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.RemoveField(
            model_name='registrotrabajo',
            name='odontologo',
        ),
        migrations.RemoveField(
            model_name='registrotrabajo',
            name='tratamiento',
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='valor_base',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='costo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Base'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Tratamiento'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tratamientos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Tratamientos')),
                ('total_examenes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Exámenes')),
                ('ganancia_neta_doctor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancia Neta Doctor')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='odontologia.atencion', verbose_name='Atención Asociada')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
        migrations.CreateModel(
            name='DetalleAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Tratamiento')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='odontologia.atencion', verbose_name='Atención')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento', verbose_name='Tratamiento')),
            ],
            options={
                'verbose_name': 'Detalle de Atención',
                'verbose_name_plural': 'Detalles de Atenciones',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.AddField(
            model_name='atencion',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.doctor', verbose_name='Doctor'),
        ),
        migrations.CreateModel(
            name='ExamenAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo del Examen')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='odontologia.atencion', verbose_name='Atención')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Examen de Atención',
                'verbose_name_plural': 'Exámenes de Atenciones',
            },
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.paciente', verbose_name='Paciente'),
        ),
        migrations.DeleteModel(
            name='Odontologo',
        ),
        migrations.DeleteModel(
            name='RegistroTrabajo',
        ),
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together={('doctor', 'paciente', 'fecha')},
        ),
    ]
