# Generated by Django 5.2.7 on 2025-10-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0003_atencion_examen_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de Crédito'), ('TD', 'Tarjeta de Débito'), ('TR', 'Transferencia')], default='EF', max_length=2, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='motivo_visita',
            field=models.CharField(default='', max_length=200, verbose_name='Motivo de la Visita'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='duracion_aproximada',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos', verbose_name='Duración Aproximada (min)'),
        ),
    ]
