# Generated by Django 5.2.7 on 2025-10-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0004_atencion_metodo_pago_atencion_motivo_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
