# Generated by Django 5.2.7 on 2025-10-25 02:15

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0005_doctor_foto_perfil'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='detalleatencion',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente_apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido del Paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente_edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad del Paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente_nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre del Paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente_rut',
            field=models.CharField(default='', max_length=15, verbose_name='RUT del Paciente'),
        ),
        migrations.AddField(
            model_name='detalleatencion',
            name='descripcion',
            field=models.TextField(default='', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción del Tratamiento'),
        ),
        migrations.AddField(
            model_name='detalleatencion',
            name='especialidad',
            field=models.CharField(choices=[('OPER', 'Operatoria'), ('ENDO', 'Endodoncia'), ('ORTO', 'Ortodoncia'), ('CIRU', 'Cirugía'), ('IMPL', 'Implantes'), ('PEDIA', 'Odontopediatría'), ('HIGI', 'Higiene Oral'), ('OTRO', 'Otro')], default='OTRO', max_length=5, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Atención'),
        ),
        migrations.AlterField(
            model_name='detalleatencion',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='examenatencion',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo del Examen'),
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='paciente',
        ),
    ]
