# Generated by Django 5.2.7 on 2025-11-04 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0007_doctor_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='total_examenes',
        ),
        migrations.AddField(
            model_name='atencion',
            name='hora_atencion',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de Atención'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente_celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular del Paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente_sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1, verbose_name='Sexo del Paciente'),
        ),
        migrations.DeleteModel(
            name='ExamenAtencion',
        ),
    ]
