# Generated by Django 5.2.7 on 2025-11-23 18:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0008_remove_boleta_total_examenes_atencion_hora_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='total_examenes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Exámenes'),
        ),
        migrations.CreateModel(
            name='ExamenAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripción del Examen')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_solicitados', to='odontologia.atencion', verbose_name='Atención')),
            ],
            options={
                'verbose_name': 'Examen Solicitado',
                'verbose_name_plural': 'Exámenes Solicitados',
            },
        ),
    ]
